# Generated by Django 4.2 on 2023-07-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='velog',
            name='author',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='velog',
            name='date',
            field=models.TextField(default=''),
        ),
    ]
