# Generated by Django 4.2 on 2023-07-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_velog_author_velog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='velog',
            name='url',
            field=models.TextField(default='http://127.0.0.1:8000/'),
        ),
    ]
