# Generated by Django 4.2 on 2023-07-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_velog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='velog',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
